# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- checkout: self
  persistCredentials: true

- script: |
    git config user.email "massoumeharmonie@gmail.com" 
    git config user.name "audreymengue"
    npm install
    npm run deploy -- -r https://$(GITHUB_PAT)@github.com/azugsdemo1
  displayName: 'npm install and build'
